#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_products:
    path: /admin/products
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: AdminArea/products.html.twig

admin_reports:
    path: /admin/reports
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: AdminArea/reports.html.twig